name: wanna_chat_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  logging: ^1.2.0

  shelf_cors_headers: ^0.1.5
  dart_frog: ^1.1.0

  #langchain: ^0.4.3
  # NOTE: Using pre-release version that includes necessary bug fixes
  langchain:
    git:
      url: https://github.com/davidmigloz/langchain_dart
      path: packages/langchain

  #langchain_openai: ^0.4.3
  # NOTE: This override can be removed when updating "langchain" to a published version.
  langchain_openai:
    git:
      url: https://github.com/davidmigloz/langchain_dart
      path: packages/langchain_openai

  #langchain_community: ^0.4.3
  # NOTE: This override can be removed when updating "langchain" to a published version.
  langchain_community:
    git:
      url: https://github.com/davidmigloz/langchain_dart
      path: packages/langchain_community

  shared_model:
    path: ../shared_model

dependency_overrides:
  # NOTE: Using pre-release version that includes necessary bug fixes. This override can be removed when updating "langchain" to a published version.
  langchain_core:
    git:
      url: https://github.com/davidmigloz/langchain_dart
      path: packages/langchain_core

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  lint: ^2.3.0
